version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db1'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - .:/var/lib/mysql